name: Run Regressivo

on:
  pull_request:
    branches: [master]

jobs:
  cypress-run:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout/Clone do projeto
      uses: actions/checkout@v3

    - name: Instalar dependencias do projeto
      run: npm install

    - name: Run testes
      uses: cypress-io/github-actions@v5
      with:
        record: true
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}